name: tika

x-net: &net
  networks:
    - tika-net
services:
  tika-init:
    container_name: tika-init
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - tika-config:/config
      - tika-extras:/tika-extras
  tika:
    container_name: tika
    image: apache/tika:latest-full
    <<: [ *net ]
    command: -c /config/config.xml
    ports:
      - "9998:9998"
    environment:
      - "AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT=true"
    volumes:
      - ./tika-output:/output
      - tika-config:/config
      - tika-extras:/tika-extras
    depends_on:
      tika-init:
        condition: service_completed_successfully
  s3mock:
    image: adobe/s3mock:latest
    hostname: s3
    <<: *net
    environment:
      #      - debug=true
      - retainFilesOnExit=false
      - root=uploads
      - initialBuckets=${BUCKET}
    ports:
      - "9090:9090" # HTTP

volumes:
  tika-config:
  tika-extras:
networks:
  tika-net: