name: tika
x-function: &function
  volumes:
    - tika-config:/config
    - tika-extras:/tika-extras
services:
  tika-init:
    build:
      context: .
      dockerfile: Dockerfile
    <<: *function
  tika:
    image: apache/tika:latest-full
    <<: *function
    command: -c /config/config.xml
    ports:
      - "9998:9998"
    environment:
      - "AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT=true"
    depends_on:
      tika-init:
        condition: service_completed_successfully

volumes:
  tika-config:
  tika-extras: