name: Run Tests
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.idea/**'
      - '*.md'
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]
jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: ${{ runner.os }}-${{ hashFiles('docker-compose.yml') }}
      - name: Start test dependency services
        run: |
          cp env.example .env
          docker compose up -d --build --force-recreate
          sleep 3 # wait for services to start
          docker ps -a
          docker logs tika-init
      - name: Run test
        script:
          - chown :35002 tika-output
          - bash ./test.sh
